global using AutoMapper;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.Extensions.Caching.Distributed;
global using Microsoft.Extensions.Caching.Memory;
global using MorningStar.Common;
global using MorningStar.Extension;
global using MorningStar.Model;
global using MorningStar.Service;
global using Newtonsoft.Json;
global using System.ComponentModel.DataAnnotations;
global using static MorningStar.Extension.CustomApiVersion;
