global using MorningStar.Infrastructure;
global using MorningStar.Model;
global using MorningStar.Service;
global using Autofac;
global using Autofac.Extensions.DependencyInjection;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using static MorningStar.Infrastructure.CustomApiVersion;
global using System.ComponentModel.DataAnnotations;
global using Newtonsoft.Json;